name: Ejecutar pruebas con pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Run tests with pytest
      run: |
        python -m pytest tests_pytest.py -v --cov=sistema --cov-report=xml
      
    - name: Upload coverage to Codecov (opcional)
      uses: codecov/codecov-action@v1
      if: success()
